### PR TITLE
Split views.py and its tests into four files each.

### PR DESCRIPTION
**Pull request by adam-thomas**
For https://github.com/incuna/incuna-groups/issues/27.  I've made no functional changes or other refactorings (as of https://github.com/incuna/incuna-groups/commit/8584f4bb54cefc8a03505c21c01f15dcf94f2ab4) since they'd be easily lost in the giant diff.  Paths for mock methods have been updated and that sort of thing.

`views.py` is now four files:
- `views/_helpers.py`
- `views/groups.py`
- `views/discussions.py`
- `views/comments.py`

The test files mirror the same structure, although they aren't in a subfolder (I tried that, but it didn't work for some reason).  Anything shared between two different kinds of model is in `_helpers.py`, including some `Comment`-creating views since they're used by `DiscussionThread`.

@incuna/backend review please?

### CODE REVIEW

**Comment by meshy** [comment]
This is great! What do you think about also having a `subscriptions` module that has all that stuff in it?

**Comment by adam-thomas** [comment]
Could do! :)

**Comment by adam-thomas** [comment]
@meshy updated :)

**Comment by meshy** [comment]
:+1:

**Pull request merged**
