### PR TITLE
Add missing migration

### PR DESCRIPTION
**Pull request by Ian-Foote**

### CODE REVIEW

**Comment by Ian-Foote** [comment]
@meshy Review?

**Comment by meshy** [comment]
migration looks good, but can you please give the file a sensible name?

**Comment by Ian-Foote** [comment]
Any ideas?

**Comment by meshy** [comment]
Well I think that polymorphic has changed the `related_name` on the `polymorphic_ctype`, at least. Perhaps `upgrade_django_polymorphic`? It might be worth finding out what version this changed in, and making sure that the version in `setup.py` is above that.

**Comment by Ian-Foote** [comment]
Updated.

**Comment by meshy** [comment]
:+1: LGTM

**Pull request merged**
