### PR TITLE
Make AddTextComment crispy-form suitable for use in DiscussionThread inline replies

### PR DESCRIPTION
**Pull request by adam-thomas**
Don't merge this yet.  It is merely a record of my flailing attempts at getting this:

ffs crispy-forms

to look like this:

proper reply form

### CODE REVIEW

**Comment by meshy** [comment]
Yeah, you know what -- we have something that works, and "fixing" it to use crispy forms is probably more effort than it is worth. I applaud your efforts, but they're probably best applied elsewhere.

**Comment by meshy** [comment]
Although, I have just discovered that the form that is currently there does not show form errors.

**Comment by adam-thomas** [comment]
Which errors can it reasonably generate?  If the text box is blank it just doesn't submit anything, which seems fine to me.  (It does refresh the page.)  I can't think of anything else it could possibly do.

**Comment by meshy** [comment]
Yeah, that's the error I had in mind. You're right, it's not the end of the world that it doesn't show up, but it is a little odd.

**Comment by meshy** [comment]
It might not be hard to introduce the form errors: https://docs.djangoproject.com/en/1.8/topics/forms/#rendering-fields-manually

**Comment by adam-thomas** [comment]
Ah yes, I did think about that.  I'll add them in.

**Pull request closed without merging**
