### PR TITLE
Polymorphise Comments

### PR DESCRIPTION
**Pull request by adam-incuna**
We're expecting to have a number of different types of comment on a post, potentially including file uploads, polls, email replies, and more. For this purpose, we need an easily-subclassed comment class.

This PR exchanges the existing `Comment` class for a `BaseComment` and removes the `body` field, moving that out to a subclass called `TextComment`.  `TextComment` provides the existing `Comment` functionality.

Don't merge just yet (if you're reading this) - needs manual verification that it works first.

### CODE REVIEW

**Comment by meshy** [comment]
Looks alright to me `:)`

**Comment by adam-incuna** [comment]
@incuna/backend review please? :)

**Comment by adam-incuna** [comment]
Oh, thanks @meshy  :)

**Comment by meshy** [comment]
I take it you've done the verification you had intended to?

**Comment by adam-incuna** [comment]
Yup, all seems present and correct.  I had to fix the delete template but that was it.

**Comment by meshy** [comment]
:+1:

**Comment by adam-incuna** [comment]
Thanks! :)

**Pull request merged**
