### PR TITLE
Add AttachedFileComment

### PR DESCRIPTION
**Pull request by adam-thomas**
This is a `FileComment` subclass that can be attached to a different comment.  It doesn't show up in the discussion thread by itself, but will instead appear as part of its parent, like so:

screenshot from 2015-12-22 10 07 48

This screenshot displays a `TextComment` and a `FileComment`, each with a different `AttachedFileComment` stapled to it.  (I created the latter in the Python shell rather than via the website itself, that'll come later.)

@incuna/backend review please?

### CODE REVIEW

**Comment by meshy** [comment]
After discussion IRL, it seems to make sense to decouple attachments from comments, making them a model in their own right.

**Comment by adam-thomas** [comment]
On it :)

**Comment by adam-thomas** [comment]
@meshy @Ian-Foote updated!

**Comment by adam-thomas** [comment]
Any more comments?

**Comment by adam-thomas** [comment]
Thanks :D

**Pull request merged**
